/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "dpw9EHDh2bM",
    title: "React Today & Tomorrow & 90% Cleaner React With Hooks",
    videoUrl: "https://youtu.be/dpw9EHDh2bM",
    categoryName: "Web Development",
    viewCount: 0,
    uploadDate: new Date(2018, 9, 26),
    description: "The first three talks from React Conf 2018 by Sophie Alpert, Dan Abramov, and Ryan Florence."
  },
  {
    _id: "8aGhZQkoFbQ",
    title: "What the heck is the event loop anyway?",
    videoUrl: "https://youtu.be/8aGhZQkoFbQ",
    categoryName: "Web Development",
    viewCount: 0,
    uploadDate: new Date(2014, 9, 9),
    description: "JavaScript programmers like to use words like, “event-loop”, “non-blocking”, “callback”, “asynchronous”, “single-threaded” and “concurrency”.",
  },
  {
    _id: "t2ypzz6gJm0",
    title: "Learn useRef in 11 Minutes",
    videoUrl: "https://youtu.be/t2ypzz6gJm0",
    categoryName: "Web Development",
    viewCount: 0,
    uploadDate: new Date(2020, 5, 9),
    description: "In this video we cover everything you need to know about the useRef hook.",
  },
  {
    _id: "kYCZPXSVvOQ",
    title: "NASA’s first software engineer: Margaret Hamilton",
    videoUrl: "https://youtu.be/kYCZPXSVvOQ",
    categoryName: "Software Engineering",
    viewCount: 0,
    uploadDate: new Date(2020, 2, 5),
    description: "Learn how Margaret Hamilton and her team of engineers built the software for the Apollo 11 mission that landed mankind on the Moon.",
  },
  {
    _id: "vFOw_m5zNCs",
    title: "Tips for Software Engineering Interviews",
    videoUrl: "https://youtu.be/vFOw_m5zNCs",
    categoryName: "Software Engineering",
    viewCount: 0,
    uploadDate: new Date(2020, 11, 30),
    description: "Insights & advice from a hiring manager at Uber & Skyscanner.",
  },
  {
    _id: "3c-iBn73dDE",
    title: "Docker Tutorial for Beginners",
    videoUrl: "https://youtu.be/3c-iBn73dDE",
    categoryName: "DevOps",
    viewCount: 0,
    uploadDate: new Date(2020, 9, 22),
    description: "Full Docker Tutorial | Complete Docker Course | Hands-on course",
  },
  {
    _id: "X48VuDVv0do",
    title: "Kubernetes Tutorial for Beginners",
    videoUrl: "https://youtu.be/X48VuDVv0do",
    categoryName: "DevOps",
    viewCount: 0,
    uploadDate: new Date(2020, 10, 6),
    description: "Full Kubernetes Tutorial | Kubernetes Course | Hands-on course with a lot of demos",
  },
  {
    _id: "scEDHsr3APg",
    title: "DevOps CI/CD Explained in 100 Seconds",
    videoUrl: "https://youtu.be/scEDHsr3APg",
    categoryName: "DevOps",
    viewCount: 0,
    uploadDate: new Date(2020, 2, 12),
    description: "Insights & advice from a hiring manager at Uber & Skyscanner.",
  },
  {
    _id: "77ZF50ve6rs",
    title: "When a physics teacher knows his stuff !!",
    videoUrl: "https://youtu.be/77ZF50ve6rs",
    categoryName: "Science & Technology",
    viewCount: 0,
    uploadDate: new Date(2020, 2, 5),
    description: "Prof. Walter Lewin best ever video on Physics",
  },
  {
    _id: "mXVGIb3bzHI",
    title: "Can Silence Actually Drive You Crazy?",
    videoUrl: "https://youtu.be/mXVGIb3bzHI",
    categoryName: "Science & Technology",
    viewCount: 0,
    uploadDate: new Date(2014, 1, 18),
    description: "Is 45 minutes really the longest anyone can stay in a perfectly silent, pitch-black room?",
  },
  {
    _id: "uyMtsyzXWd4",
    title: "Inside the black hole image that made history",
    videoUrl: "https://youtu.be/uyMtsyzXWd4",
    categoryName: "Science & Technology",
    viewCount: 0,
    uploadDate: new Date(2019, 4, 10),
    description: "At the center of a galaxy more than 55 million light-years away, there's a supermassive black hole with the mass of several billion suns.",
  },
];
